name: 'GSA/grace-style-guide'
description: 'Coding Style Guide for GSA GRACE Project'
license: null
openSourceProject: 1
governmentWideReuseProject: 1
tags:
    - open-source
    - opensource
    - grace
    - devsecops
contact:
    email: devsecops-core@gsa.gov
